# docker-compose.yaml
version: "3"
services:
  mongo:
    image: "mongo:4.4"
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=doodle_db
  mongo-data:
    image: "mongo:4.4"
    links:
      - mongo
    volumes:
      - ./mongo:/mongo-data
    command:
      'bash -c "mongoimport  --db doodle_db --collection polls  --host mongo --type json --file /mongo-data/polls.json --jsonArray"'